# -*- coding: utf-8 -*-
"""GaussLegendre.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xUUNcXh3sgUKQcqtPyRKuSWG4fUVN1nV
"""

import numpy as np
import math

def gauss_legendre(f, a, b, n):
    t, w = np.polynomial.legendre.leggauss(n)
    mid  = 0.5 * (a + b)
    rad  = 0.5 * (b - a)
    xk   = mid + rad * t
    return float(rad * np.dot(w, f(xk)))

def gauss_legendre_automatic(f, a, b, tol=1e-10, n_awal=2, n_maks=256):
    n = max(2, n_start)
    prev = None
    hist = []
    while True:
        In = gauss_legendre(f, a, b, n)
        hist.append((n, In))
        if prev is not None and abs(In - prev) < tol:
            return In, n, hist
        if n >= n_max:
            return In, n, hist
        prev = In
        n = n*2 if n < 32 else n + 16

if __name__ == "__main__":
    f1 = lambda x: np.cos(x)
    f2 = lambda x: x**2
    I1_n4 = gauss_legendre(f1, 0.0, math.pi/2, n=4)
    I2_n2 = gauss_legendre(f2, 0.0, 1.0,      n=2)

print("∫_0^{π/2} cos x dx (n=4) =", I1_n4)
print("∫_0^1 x^2 dx (n=2)       =", I2_n2)